// GENERATED by cpu-cache-lab/scripts/export_lab_data.py — do not edit by hand.
// Source of truth: cpu-cache-lab/results/*.csv + results/machine.json.
// Regenerate after a lab rerun:  python cpu-cache-lab/scripts/export_lab_data.py

// Machine: 13th Gen Intel(R) Core(TM) i5-1334U — measured 2026-09-29, g++ 14.2.0, -O3 -march=native -static-libstdc++ -static-libgcc

export interface DetectedCache {
  level: number;
  type: string;
  sizeBytes: number;
  lineSize: number;
  ways: number;
}

export interface MachineInfo {
  cpu: string;
  logicalCpus: number;
  tscGhz: number;
  date: string;
  caches: DetectedCache[];
}

export const MACHINE: MachineInfo = {
  cpu: "13th Gen Intel(R) Core(TM) i5-1334U",
  logicalCpus: 12,
  tscGhz: 2.496,
  date: "2026-09-29",
  caches: [
    { level: 1, type: "data", sizeBytes: 49152, lineSize: 64, ways: 12 },
    { level: 1, type: "instruction", sizeBytes: 32768, lineSize: 64, ways: 8 },
    { level: 2, type: "unified", sizeBytes: 1310720, lineSize: 64, ways: 10 },
    { level: 3, type: "unified", sizeBytes: 12582912, lineSize: 64, ways: 12 },
  ],
};

/** Pointer-chase latency plateaus per level (medians of the staircase bands; L3 = first step past L2). */
export const LEVEL_NS = {
  l1: 1.18,
  l2: 3.56,
  l3: 9.5,
  dram: 125.31,
};

/** Stage 1: pointer-chase median latency per dependent load vs working-set size. */
export const STAIRCASE: { bytes: number; ns: number }[] = [
    { bytes: 4096, ns: 1.18 },
    { bytes: 5760, ns: 1.16 },
    { bytes: 8192, ns: 1.17 },
    { bytes: 11584, ns: 1.22 },
    { bytes: 16384, ns: 1.19 },
    { bytes: 23168, ns: 1.15 },
    { bytes: 32768, ns: 1.19 },
    { bytes: 46336, ns: 1.18 },
    { bytes: 65536, ns: 3.47 },
    { bytes: 92672, ns: 3.5 },
    { bytes: 131072, ns: 3.53 },
    { bytes: 185344, ns: 3.56 },
    { bytes: 262144, ns: 3.57 },
    { bytes: 370688, ns: 3.51 },
    { bytes: 524288, ns: 4.01 },
    { bytes: 741440, ns: 4.4 },
    { bytes: 1048576, ns: 5.15 },
    { bytes: 1482880, ns: 9.5 },
    { bytes: 2097152, ns: 14.17 },
    { bytes: 2965760, ns: 15.3 },
    { bytes: 4194304, ns: 25.33 },
    { bytes: 5931584, ns: 45.43 },
    { bytes: 8388608, ns: 60.11 },
    { bytes: 11863232, ns: 95.18 },
    { bytes: 16777216, ns: 102.86 },
    { bytes: 23726528, ns: 116.29 },
    { bytes: 33554432, ns: 139.82 },
    { bytes: 47453120, ns: 121.43 },
    { bytes: 67108864, ns: 121.12 },
    { bytes: 94906240, ns: 121.84 },
    { bytes: 134217728, ns: 125.52 },
    { bytes: 189812480, ns: 125.31 },
    { bytes: 268435456, ns: 130.97 },
];

/** TLB benchmark: hop latency vs number of distinct 4 KiB pages touched. */
export const TLB_STAIRCASE: { pages: number; ns: number }[] = [
    { pages: 1, ns: 1.14 },
    { pages: 2, ns: 1.15 },
    { pages: 4, ns: 1.15 },
    { pages: 5, ns: 1.14 },
    { pages: 8, ns: 1.14 },
    { pages: 11, ns: 1.15 },
    { pages: 16, ns: 1.14 },
    { pages: 22, ns: 1.14 },
    { pages: 32, ns: 1.15 },
    { pages: 45, ns: 1.14 },
    { pages: 64, ns: 1.14 },
    { pages: 90, ns: 1.14 },
    { pages: 128, ns: 2.49 },
    { pages: 181, ns: 2.67 },
    { pages: 256, ns: 2.69 },
    { pages: 362, ns: 2.72 },
    { pages: 512, ns: 2.78 },
    { pages: 724, ns: 2.78 },
    { pages: 1024, ns: 5.1 },
    { pages: 1448, ns: 4.99 },
    { pages: 2048, ns: 5.83 },
    { pages: 2896, ns: 10.39 },
    { pages: 4096, ns: 11.25 },
    { pages: 5792, ns: 11.83 },
    { pages: 8192, ns: 12.28 },
    { pages: 11585, ns: 12.94 },
    { pages: 16384, ns: 14.57 },
];

/** Stage 3: matmul n=1024 ladder, best measured run per implementation. */
export interface LadderRun { impl: string; label: string; gflops: number; tile: number | null; threads: number; note: string }
export const MATMUL_LADDER: LadderRun[] = [
    { impl: "plain-ijk", label: "Naive ijk", gflops: 0.67, tile: null, threads: 1, note: "a miss per multiply \u2014 DRAM latency on the critical path" },
    { impl: "plain-ikj", label: "Loop order \u2192 ikj", gflops: 10.35, tile: null, threads: 1, note: "inner loop walks C and B rows contiguously: 15\u00d7 faster, zero cleverness" },
    { impl: "tiled-ikj", label: "+ Tiling", gflops: 17.11, tile: 96, threads: 1, note: "best tile: works in cache-sized squares" },
    { impl: "avx2+fma", label: "+ AVX2/FMA", gflops: 10.82, tile: null, threads: 1, note: "SIMD alone doesn't fix the memory bound" },
    { impl: "4x4-regblock+pack(avx2)", label: "+ Reg-block & pack", gflops: 16.03, tile: 256, threads: 1, note: "registers as the innermost cache level" },
    { impl: "4x4-regblock+pack(avx2)+openmp(12thr)", label: "+ OpenMP \u00d712", gflops: 22.22, tile: 256, threads: 12, note: "12 threads on the same optimized core" },
];
/** Loop-order fixup alone (naive ijk → ikj). */
export const MATMUL_LOOP_ORDER_SPEEDUP = 15.5;

/** Stage 7: adjacent vs padded per-core counters, 12 threads × 5M increments. */
export const FALSE_SHARING = {
  adjacentMps: 53305851,
  paddedMps: 1221971039,
  slowdown: 22.9,
};

/** Stage 2: dependent-load latency vs stride — the 64-byte line made visible. */
export const CACHE_LINE_LATENCY: { stride: number; ns: number }[] = [
    { stride: 8, ns: 14.3 },
    { stride: 16, ns: 25.7 },
    { stride: 32, ns: 48.8 },
    { stride: 64, ns: 108.8 },
    { stride: 128, ns: 112.2 },
    { stride: 256, ns: 112.8 },
];

/** Stage 2: k lines resident in one L1 set (4 KiB set period) — the cliff is the associativity. */
export const ASSOC_SWEEP: { k: number; ns: number }[] = [
    { k: 2, ns: 1.17 },
    { k: 3, ns: 1.14 },
    { k: 4, ns: 1.13 },
    { k: 5, ns: 1.14 },
    { k: 6, ns: 1.14 },
    { k: 7, ns: 1.15 },
    { k: 8, ns: 1.16 },
    { k: 9, ns: 1.13 },
    { k: 10, ns: 1.15 },
    { k: 11, ns: 1.14 },
    { k: 12, ns: 1.14 },
    { k: 13, ns: 2.93 },
    { k: 14, ns: 3.51 },
    { k: 15, ns: 3.58 },
    { k: 16, ns: 3.49 },
    { k: 17, ns: 3.6 },
    { k: 18, ns: 3.46 },
    { k: 19, ns: 3.46 },
    { k: 20, ns: 3.57 },
    { k: 21, ns: 3.56 },
    { k: 22, ns: 3.23 },
    { k: 23, ns: 3.57 },
    { k: 24, ns: 3.52 },
    { k: 25, ns: 3.56 },
    { k: 26, ns: 3.37 },
    { k: 27, ns: 3.42 },
    { k: 28, ns: 3.32 },
    { k: 29, ns: 3.38 },
    { k: 30, ns: 3.31 },
    { k: 31, ns: 3.4 },
    { k: 32, ns: 3.38 },
];

/** Stage 6: coherence simulator (4 cores, 200 iters) — bus traffic per protocol/workload. */
export interface CoherenceRun { protocol: string; workload: string; busTransactions: number; invalidations: number; coherenceMisses: number }
export const COHERENCE: CoherenceRun[] = [
    { protocol: "MSI", workload: "private_counters", busTransactions: 8, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MSI", workload: "adjacent_counters", busTransactions: 1600, invalidations: 799, coherenceMisses: 796 },
    { protocol: "MSI", workload: "padded_counters", busTransactions: 8, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MSI", workload: "read_only_shared", busTransactions: 4, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MSI", workload: "producer_consumer", busTransactions: 400, invalidations: 199, coherenceMisses: 199 },
    { protocol: "MSI", workload: "tas_lock", busTransactions: 1799, invalidations: 999, coherenceMisses: 996 },
    { protocol: "MSI", workload: "ttas_lock", busTransactions: 1199, invalidations: 799, coherenceMisses: 796 },
    { protocol: "MESI", workload: "private_counters", busTransactions: 4, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MESI", workload: "adjacent_counters", busTransactions: 1599, invalidations: 799, coherenceMisses: 796 },
    { protocol: "MESI", workload: "padded_counters", busTransactions: 4, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MESI", workload: "read_only_shared", busTransactions: 4, invalidations: 0, coherenceMisses: 0 },
    { protocol: "MESI", workload: "producer_consumer", busTransactions: 400, invalidations: 199, coherenceMisses: 199 },
    { protocol: "MESI", workload: "tas_lock", busTransactions: 1799, invalidations: 999, coherenceMisses: 996 },
    { protocol: "MESI", workload: "ttas_lock", busTransactions: 1199, invalidations: 799, coherenceMisses: 796 },
];
